### ISSUE TITLE
Usar uma estratégia de script no frontend para evitar que o cliente envie dados que não estejam no datalist (campos de curso)

### ISSUE THREAD

**Issue by lucas-jdev** [pgiselio/JOLOS#15]
sugestão base para a implementação do script:
https://www.jotform.com/blog/html5-datalists-what-you-need-to-know-78024/

**Comment by pgiselio** [comment]
Provável uso de select personalizado (ainda a ser feito)

**Comment by pgiselio** [comment]
Solução temporária implementada 👍
