### ISSUE TITLE
erro de digitação kkkk 

### ISSUE THREAD

**Issue by pgiselio** [pgiselio/JOLOS#18]
![image](https://user-images.githubusercontent.com/60955300/163683030-c91fbe25-9be9-4a1e-af9d-f2f933e1bcc0.png)

**Comment by lucas-jdev** [comment]
solicito que faça um novo deploy da aplicação do backend para testar se o erro foi corrigido, uma vez que não tenho acesso a fazer deploy manual

**Comment by pgiselio** [comment]
Leia o artigo que lhe mandei 👍 
ninguém tem autorização de fazer pelo site tem que fazer umas coisas lá

**Comment by lucas-jdev** [comment]
correção implementada com êxito.
