### ISSUE TITLE
Problema ao patchear status da vaga (Tem foto)

### ISSUE THREAD

**Issue by pgiselio** [pgiselio/JOLOS#19]
![image](https://user-images.githubusercontent.com/60955300/163751518-8214ceb8-2a11-4e78-bfcd-b43fddd96b68.png)

O que eu passei:

![image](https://user-images.githubusercontent.com/60955300/163751672-07459c50-d4e7-4014-ad3c-8352bc5cbc82.png)

Tentei desse mesmo jeito só que com a descrição e funcionou.

Fé 🙏

**Comment by lucas-jdev** [comment]
implementação feita com sucesso usando a depedência do json-patch.
